[package]
name = "reginald_db"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
sqlite = { workspace = true }
reginald_ast = { workspace = true }
reginald_conf = { workspace = true }

[dev-dependencies]
uuid = { workspace = true, features = ["v4"] }