command = {
	log_cmd
    | add_cmd
    | funds_cmd
    | bag_cmd
    | find_cmd
    | take_cmd
}

log_cmd = { ( ^"log" ~ " " ~ ( date | "all" | '0'..'9'+ ) ~ flag? ) }
add_cmd = { ( ^"add" ~ " " ~ ( money | item ) ~ flag? ) }
funds_cmd = { ( ^"funds" ~ " " ~ flag? ) }
bag_cmd = { ( ^"bag" ~ " " ~ flag? ) }
find_cmd = { ( ^"find" ~ " " ~ flag? ) }
take_cmd = { ( ^"take" ~ " " ~ flag? ) }

item = { ( ASCII_DIGIT+ ~ item_flag* ) }

item_flag = {
	( ^"-d" ~ " " ~ ASCII_DIGIT+ )
    | ( ^"-c" ~ " " ~ money )
    | ( ^"-n" ~ " " ~ ( "0" | '0'..'9'+ ) )
}

money = { ( ( "0" | '0'..'9'+ ) ~ currency_ident? ) }

currency_ident = {
	gold_ident
    | silver_ident
    | copper_ident
    | electrum_ident
    | platinum_ident
}

copper_ident = { ( ^"c" ) | ( ^"cp" ) | ( ^"copper" ) }
silver_ident = { ( ^"s" ) | ( ^"sp" ) | ( ^"silver" ) }
gold_ident = { ( ^"g" ) | ( ^"gp" ) | ( ^"gold" ) }
electrum_ident = { ( ^"e" ) | ( ^"ep" ) | ( ^"electrum" ) }
platinum_ident = { ( ^"p" ) | ( ^"pp" ) | ( ^"platinum" ) }

date = { 
	( '0'..'9'+ ~ "-" ~ '0'..'9'+ ~ "-" ~ '0'..'9'+ ) 
    | ( '0'..'9'+ ~ "." ~ '0'..'9'+ ~ "." ~ '0'..'9'+ )
    | ( '0'..'9'+ ~ "/" ~ '0'..'9'+ ~ "/" ~ '0'..'9'+ )
}

flag = {
	( ^"-h" ) | ( "--help" )
}

bot = {
	( ^"!reginald" )
	| ( ^"!regi" )
    | ( ^"!hare" )
}


input = { bot ~ " " ~ command | bot }
