
input = { bot ~ command ~ ( flag_affix ~ flag )? }

command = {
	log_cmd
    | add_cmd
    | funds_cmd
    | bag_cmd
    | find_cmd
    | take_cmd
}

WHITESPACE = _{ " " }

log_all = { ( ^"all" ) } 
session_nr = { ( '0'..'9'+ ~ "s" ) }

log_cmd = { ( ^"log" ~ ( date | log_all | session_nr ) ) }
add_cmd = { ( ^"add" ~ ( money+ | item ~ ( "|" ~ item )* ) ) }
funds_cmd = { ( ^"funds" ) }
bag_cmd = { ( ^"bag" ) }
find_cmd = { ( ^"find" ~ item ~ ( "|" ~ item )* ) }
take_cmd = { ( ^"take" ~ ( money+ | item ~ ( "|" ~ item )* ) ) }

SEPERATOR = { ( "\"" ) }

item = { ( item_name ~
	(
    item_description
    | item_count
    | item_cost
    | item_tag
    )*  
) }

word = { ASCII_ALPHANUMERIC* }

item_name = { ( "\"" ~ word ~ "\"" ) }
item_description = { ( "\"" ~ word ~ "\"" ) }
item_cost = { ( money ) }
item_count = { ( ^"0x" | '1'..'9' ~ ( '0'..'9' )* ~ ^"x" ) | ( ^"x0" | ^"x" ~ '1'..'9' ~ ( '0'..'9' )* ) }
item_tag = { ( ^"-tag=" ~ "\"" ~ word ~ "\"" ) }

money = { ( currency_value ~ currency_ident? ) }

currency_value = { ( "0" | '1'..'9' ~ ( '0'..'9' )* ) }

currency_ident = {
	gold_ident
    | silver_ident
    | copper_ident
    | electrum_ident
    | platinum_ident
}

copper_ident = { ( ^"cp" ) | ( ^"copper" ) | ( ^"c" ) }
silver_ident = { ( ^"sp" ) | ( ^"silver" ) | ( ^"s" ) }
gold_ident = { ( ^"gp" ) | ( ^"gold" ) | ( ^"g" ) }
electrum_ident = { ( ^"ep" ) | ( ^"electrum" ) | ( ^"e" ) }
platinum_ident = { ( ^"pp" ) | ( ^"platinum" ) | ( ^"p" ) }

date = { 
	( date_day ~ date_sep ~ date_month ~ date_sep ~ date_year ) 
}

date_sep = { "." | "-" | "/" }
date_day = { ( ( "0" )? ~ '1'..'9' | '1'..'3' ~ '0'..'9' ) }
date_month = { ( "10" | "11" | "12" | ( "0" )? ~ '1'..'9' ) }
date_year = { ( '0'..'9'{ 4 } | ( '0'..'9' ~ '0'..'9' ) ) }

flag = {
	( ^"h" ) | ( ^"help" )
}

flag_affix = { ( "-" | "--" ) }

bot = {
	( ^"!reginald" )
	| ( ^"!regi" )
    | ( ^"!hare" )
}

